name: Update Changelog

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changelog if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet CHANGELOG.md; then
            echo "No changes to changelog"
          else
            git add CHANGELOG.md
            git commit -m "chore: update changelog [skip ci]"
            git push
          fi
